name: todos_repository
description: A repository that handles todo related requests.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.7

dependencies:
  path: ^1.9.0
  todo_api:
    path: ../todo_api

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
