name: todos_repository
description: A repository that handles todo related requests.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.7

dependencies:
  connectivity_plus: ^7.0.0
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  todo_api:
    path: ../todo_api

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  lints: ^6.0.0
  test: ^1.25.6
